=== xavig-icv/0373-llenguatge-de-marques/03_XML_JSON/03_validacio_xsd/exemples/cataleg.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="cataleg">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="joc" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="titol" type="xs:string" />
              <xs:element name="genere">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="RPG" />
                    <xs:enumeration value="Aventura" />
                    <xs:enumeration value="Esports" />
                    <xs:enumeration value="Estratègia" />
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="any" type="xs:positiveInteger" />
              <xs:element name="preu">
                <xs:simpleType>
                  <xs:restriction base="xs:decimal">
                    <xs:minInclusive value="0" />
                    <xs:maxInclusive value="999.99" />
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="disponible" type="xs:boolean" />
            </xs:sequence>
            <xs:attribute name="id" type="xs:positiveInteger" use="required" />
            <xs:attribute name="plataforma" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== xavig-icv/0373-llenguatge-de-marques/03_XML_JSON/03_validacio_xsd/exemples/cataleg-jocs.xml
<?xml version="1.0" encoding="UTF-8"?>
<cataleg xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cataleg.xsd">
  <joc id="1" plataforma="PC">
    <titol>The Witcher 3</titol>
    <genere>RPG</genere>
    <any>2015</any>
    <preu>19.99</preu>
    <disponible>true</disponible>
  </joc>
  <joc id="2" plataforma="PS5">
    <titol>Horizon Forbidden West</titol>
    <genere>Aventura</genere>
    <any>2022</any>
    <preu>49.99</preu>
    <disponible>true</disponible>
  </joc>
  <joc id="3" plataforma="Switch">
    <titol>The Legend of Zelda: Tears of the Kingdom</titol>
    <genere>Aventura</genere>
    <any>2023</any>
    <preu>59.99</preu>
    <disponible>false</disponible>
  </joc>
</cataleg>
